name: Build in Copr
description: Action that build a copr project through Packit
inputs:
  path:
    description: Working directory where .packit.yaml is
    required: false
  owner:
    description: Copr user/group
    required: false
  project:
    description: Copr project
    required: false
  package:
    description: Packit package to build
    required: false
runs:
  using: node20
  main: ../dist/build-copr/index.js
