name: pre-commit

on:
  workflow_call:

permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0

  husky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - name: Run npm style-checks
        run: |
          npm run format
          npm run lint

  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Compare the expected and actual dist/ directories
        id: diff
        run: |
          if [[ ! -z $(git status --porcelain dist | grep -E "^.\S") ]]; then
            echo "Detected uncommitted changes after build.  See status below or the uploaded dist folder:"
            echo "Please run: npm build && npm package && git add dist/"
            echo "Currently cannot automatically push a git commit because it will not re-trigger the CI"
            git status dist
            exit 1
          fi

      - if: ${{ failure() && steps.diff.outcome == 'failure' }}
        name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
