name: "build-test"
on:
  workflow_call:

jobs:
  test-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm install
      - name: Run npm tests
        run: |
          npm run build
          npm run test
  test-action: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: [ test-npm ]
    steps:
      - uses: actions/checkout@v3
      - name: Run github action itself
        uses: ./
